### ISSUE TITLE
ProcessFluoresenceTraces not plotting ROI's fluoresence traces

### ISSUE THREAD

**Issue by daiyunli** [zebrain-lab/Toolbox-Romano-et-al#7]
Hi,

I am having some trouble getting fluorescence traces to plot when using the ProcessFluoresenceTraces.m file. I am using the test data files provided(OT_reg_smooth). Using the file results in a plot with labeled axes but no fluorescence traces are drawn.

Edit: It seems like my deltaFOF is all NaN.

Thank you

**Comment by sebromano** [comment]
Hi,

I cannot reproduce this issue with the test data and default parameters. Indeed, if your deltaFoF consists of NaNs, they won't be plotted. Could you tell me which parameters and options you used?
